# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_appointment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(default=b'<function now at 0x0000000002F9E588>', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='main.User'),
            preserve_default=False,
        ),
    ]
