# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_appointment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='updated_at',
        ),
    ]
