# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20170224_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(default=b"<class 'apps.main.models.User'>", on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='main.User'),
        ),
    ]
